=== AndLvovSky/XML-parser/src/main/resources/device.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:complexType name="typeTemplate">
	<xs:all>
		<xs:element name="periphery" type="xs:boolean"/>
		<xs:element name="energyConsumption" type="xs:positiveInteger"/>
		<xs:element name="withCooler" type="xs:boolean"/>
		<xs:element name="componentGroup">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="input_device"/>
					<xs:enumeration value="output_device"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:element>
		<xs:element name="port">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="COM"/>
					<xs:enumeration value="USB"/>
					<xs:enumeration value="LPT"/>
					<xs:enumeration value="VGA"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:element>
	</xs:all>
</xs:complexType>

<xs:element name="device">
	<xs:complexType>
		<xs:all>
			<xs:element name="name" type="xs:string"/>
			<xs:element name="origin" type="xs:string"/>
			<xs:element name="price">
				<xs:simpleType>
					<xs:restriction base="xs:decimal">
						<xs:minExclusive value="0"/>
						<xs:maxInclusive value="100000"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="type" type="typeTemplate"/>
		</xs:all>
		<xs:attribute name="id" type="xs:ID"/>
		<xs:attribute name="critical" type="xs:boolean"/>
	</xs:complexType>
</xs:element>

</xs:schema>

=== AndLvovSky/XML-parser/src/test/resources/xml/valid_device.xml
<?xml version="1.0" encoding="UTF-8"?>
<device id="id-1" critical="true"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="../xsd/device.xsd">
	<name>Display AGK-1203, 20 inch, IPS</name>
	<origin>USA</origin>
	<price>200.75</price>
	<type>
		<periphery>true</periphery>
		<energyConsumption>50</energyConsumption>
		<withCooler>false</withCooler>
		<componentGroup>OUTPUT_DEVICE</componentGroup>
		<port>VGA</port>
	</type>
</device>
